<a href="https://colab.research.google.com/github/Swetha-latha/genai/blob/main/genai1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd

df = pd.read_csv('/content/Twitter Sentiments (1).csv')
df=df.drop(columns=['id', 'label'])
df.head()

                                               tweet
0  @user when a father is dysfunctional and is so...
1  @user @user thanks for #lyft credit i can't us...
2                                bihday your majesty
3  #model   i love u take with u all the time in ...
4             factsguide: society now    #motivation

In [ ]:
!pip install nltk

Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (3.9.1)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk) (8.4.2)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk) (4.67.3)

In [ ]:
import re
import string
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer, PorterStemmer
from nltk.tokenize import word_tokenize

# Download necessary NLTK data
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('punkt')
nltk.download('punkt_tab') # Added to address LookupError

# Initialize lemmatizer and stemmer
lemmatizer = WordNetLemmatizer()
stemmer = PorterStemmer()
stop_words = set(stopwords.words('english'))

def preprocess_text(text):
    # Convert to lowercase
    text = text.lower()

    # Remove punctuation
    text = text.translate(str.maketrans('', '', string.punctuation))

    # Tokenization
    tokens = word_tokenize(text)

    # Stop word removal and Lemmatization
    lemmatized_tokens = [lemmatizer.lemmatize(word) for word in tokens if word not in stop_words]

    # Stemming
    stemmed_tokens = [stemmer.stem(word) for word in lemmatized_tokens]

    return ' '.join(stemmed_tokens)

# Apply the preprocessing function to the 'tweet' column
df['processed_tweet'] = df['tweet'].apply(preprocess_text)

# Display the original and processed tweets
display(df[['tweet', 'processed_tweet']].head())

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

,tweet,processed_tweet
0,@user when a father is dysfunctional and is so...,user father dysfunct selfish drag kid dysfunct...
1,@user @user thanks for #lyft credit i can't us...,user user thank lyft credit cant use caus dont...
2,bihday your majesty,bihday majesti
3,#model i love u take with u all the time in ...,model love u take u time urã°âââ± ã°âââã°...
4,factsguide: society now #motivation,factsguid societi motiv

In [ ]:
display(df.head())

,tweet,processed_tweet
0,@user when a father is dysfunctional and is so...,user father dysfunct selfish drag kid dysfunct...
1,@user @user thanks for #lyft credit i can't us...,user user thank lyft credit cant use caus dont...
2,bihday your majesty,bihday majesti
3,#model i love u take with u all the time in ...,model love u take u time urã°âââ± ã°âââã°...
4,factsguide: society now #motivation,factsguid societi motiv

In [ ]:
display(df)

,tweet,processed_tweet
0,@user when a father is dysfunctional and is so...,user father dysfunct selfish drag kid dysfunct...
1,@user @user thanks for #lyft credit i can't us...,user user thank lyft credit cant use caus dont...
2,bihday your majesty,bihday majesti
3,#model i love u take with u all the time in ...,model love u take u time urã°âââ± ã°âââã°...
4,factsguide: society now #motivation,factsguid societi motiv
...,...,...
31957,ate @user isz that youuu?Ã°ÂÂÂÃ°ÂÂÂÃ°ÂÂ...,ate user isz youuuã°âââã°âââã°âââã°â...
31958,to see nina turner on the airwaves trying to w...,see nina turner airwav tri wrap mantl genuin h...
31959,listening to sad songs on a monday morning otw...,listen sad song monday morn otw work sad
31960,"@user #sikh #temple vandalised in in #calgary,...",user sikh templ vandalis calgari wso condemn act
31961,thank you @user for you follow,thank user follow

In [ ]:
print('List of English stop words used:')
print(stop_words)

List of English stop words used:
{'shouldn', "didn't", 'should', "they'd", 've', 'you', 'up', 'm', 'be', 'don', 'it', "you'd", 'wouldn', 'yourself', 'won', "you'll", 'when', "aren't", 'too', 'been', "couldn't", 'itself', 'my', 'same', 'their', 'on', 'not', 'its', 'because', 'himself', 'about', 'doesn', "they're", 'above', 'him', 'why', "haven't", 'whom', 'ain', 'with', 'each', 'having', 'doing', 'while', 'before', 'out', "should've", "he'd", 'there', "she's", 'being', "don't", 'most', 'such', "she'll", "it'd", 'he', 'wasn', 'ours', "needn't", 'd', 'or', "they'll", 'again', "mustn't", 'all', 'which', 'few', 't', 'your', 'then', 'how', 'yours', 'to', 'that', 'his', 'an', "wasn't", 'i', 'isn', 'by', 'very', 'off', 'are', "it's", 'against', "i'll", 'yourselves', 'y', 's', 'a', 'in', 'her', 'no', 'between', 'both', 'during', 'from', "he'll", "i've", "that'll", "you've", 'only', 'mustn', 'hadn', 'does', 'has', 'we', 'didn', 'those', 'hasn', 'have', "shouldn't", "shan't", 'down', 'through', 'here', "hasn't", 'herself', 'o', 'ourselves', 'further', 'haven', 'any', 'is', 'couldn', "we're", 'under', 'she', 'weren', 'as', 'for', "won't", 'can', "we've", 'did', 're', "hadn't", "he's", 'the', "i'd", 'am', 'than', 'ma', 'our', 'just', 'of', 'they', "we'll", "wouldn't", 'had', "mightn't", 'myself', 'themselves', 'theirs', "it'll", 'once', 'more', 'over', "she'd", 'them', 'now', 'after', 'so', 'was', "i'm", 'into', 'me', 'at', 'other', 'shan', 'some', "they've", 'these', 'hers', 'and', 'were', 'where', "isn't", 'if', 'but', 'mightn', 'will', "weren't", 'below', 'this', "you're", 'who', 'what', "we'd", 'do', 'until', 'aren', 'nor', "doesn't", 'll', 'own', 'needn'}

In [ ]:
from nltk.tokenize import word_tokenize

def only_tokenize(text):
    # Convert to lowercase first, as tokenization is usually done on lowercase text
    text = text.lower()
    # Remove punctuation (as done in preprocess_text before tokenization)
    text = text.translate(str.maketrans('', '', string.punctuation))
    return word_tokenize(text)

df['tokenized_tweet'] = df['tweet'].apply(only_tokenize)
display(df[['tweet', 'tokenized_tweet']].head())

,tweet,tokenized_tweet
0,@user when a father is dysfunctional and is so...,"[user, when, a, father, is, dysfunctional, and..."
1,@user @user thanks for #lyft credit i can't us...,"[user, user, thanks, for, lyft, credit, i, can..."
2,bihday your majesty,"[bihday, your, majesty]"
3,#model i love u take with u all the time in ...,"[model, i, love, u, take, with, u, all, the, t..."
4,factsguide: society now #motivation,"[factsguide, society, now, motivation]"

In [ ]:
from nltk.tokenize import sent_tokenize

def sentence_tokenize_text(text):
    return sent_tokenize(text)

df['sentence_tokenized_tweet'] = df['tweet'].apply(sentence_tokenize_text)
display(df[['tweet', 'sentence_tokenized_tweet']].head())

,tweet,sentence_tokenized_tweet
0,@user when a father is dysfunctional and is so...,[@user when a father is dysfunctional and is s...
1,@user @user thanks for #lyft credit i can't us...,[@user @user thanks for #lyft credit i can't u...
2,bihday your majesty,[bihday your majesty]
3,#model i love u take with u all the time in ...,[#model i love u take with u all the time in...
4,factsguide: society now #motivation,[factsguide: society now #motivation]

In [ ]:
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize
import string

lemmatizer = WordNetLemmatizer()

def only_lemmatize(text):
    # Convert to lowercase
    text = text.lower()
    # Remove punctuation
    text = text.translate(str.maketrans('', '', string.punctuation))
    # Tokenization
    tokens = word_tokenize(text)
    # Lemmatization
    lemmatized_tokens = [lemmatizer.lemmatize(word) for word in tokens]
    return ' '.join(lemmatized_tokens)

df['lemmatized_tweet'] = df['tweet'].apply(only_lemmatize)
display(df[['tweet', 'lemmatized_tweet']].head())

,tweet,lemmatized_tweet
0,@user when a father is dysfunctional and is so...,user when a father is dysfunctional and is so ...
1,@user @user thanks for #lyft credit i can't us...,user user thanks for lyft credit i cant use ca...
2,bihday your majesty,bihday your majesty
3,#model i love u take with u all the time in ...,model i love u take with u all the time in urã...
4,factsguide: society now #motivation,factsguide society now motivation

In [ ]:
from nltk.stem import PorterStemmer
from nltk.tokenize import word_tokenize
import string
from nltk.corpus import stopwords

stemmer = PorterStemmer()
stop_words = set(stopwords.words('english'))

def only_stem(text):
    # Convert to lowercase
    text = text.lower()
    # Remove punctuation
    text = text.translate(str.maketrans('', '', string.punctuation))
    # Tokenization
    tokens = word_tokenize(text)
    # Stop word removal
    filtered_tokens = [word for word in tokens if word not in stop_words]
    # Stemming
    stemmed_tokens = [stemmer.stem(word) for word in filtered_tokens]
    return ' '.join(stemmed_tokens)

df['stemmed_tweet'] = df['tweet'].apply(only_stem)
display(df[['tweet', 'stemmed_tweet']].head())

,tweet,stemmed_tweet
0,@user when a father is dysfunctional and is so...,user father dysfunct selfish drag kid dysfunct...
1,@user @user thanks for #lyft credit i can't us...,user user thank lyft credit cant use caus dont...
2,bihday your majesty,bihday majesti
3,#model i love u take with u all the time in ...,model love u take u time urã°âââ± ã°âââã°...
4,factsguide: society now #motivation,factsguid societi motiv